### ISSUE TITLE
Android Actionsheet not showing completely

### ISSUE THREAD

**Issue by jrichardlai** [exponentjs/react-native-action-sheet#3]
I have an issue with Android. The `Actionsheet` is cut off at the end, the reason is that `Dimensions.get('window').height` seems to include the Status Bar and Soft Menu Bar height, I used a library to get the screen height without the extra https://github.com/jaysoo/react-native-extra-dimensions-android, I have a branch that allows to pass screenHeight as a prop: https://github.com/taskrabbit/react-native-action-sheet/tree/pass-screenheight-props 

Any thought of how to resolve this without passing it? 

Not sure if `screenHeight` is the best variable name either.

**Comment by jesseruder** [comment]
I think it'd be better to use `bottom` instead of `top` here:
```
<Animated.View style={[styles.sheetContainer, {
  top: this.state.sheetY,
}]}>
```
do you see anything wrong with that approach?

**Comment by jrichardlai** [comment]
Yes that'll be better. I think I tried that it didn't worked for me, I'll try again on Monday.

**Comment by jrichardlai** [comment]
https://github.com/exponentjs/react-native-action-sheet/pull/4 I got it working with bottom @jesseruder

**Comment by jesseruder** [comment]
Looks good. Thanks!
