### ISSUE TITLE
How to use it with react-native-simple-router

### ISSUE THREAD

**Issue by WhatAKitty** [exponentjs/react-native-action-sheet#5]
Hello,
    When I use react-native-simple-router, I got nothing but a empty page. What I use is wrapping `<Router/>`,such as: `<ActionSheet><Router/></ActionSheet>`

**Comment by sibeliusseraphini** [comment]
this works fine

```jsx
<ActionSheet ref={component => this._actionSheetRef = component}>
   <View>
      <Router />
   </View>
</ActionSheet>
```

**Comment by WhatAKitty** [comment]
@sibeliusseraphini Thanks!
